Pizza_site/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from blog import views
from cooks import views
from Pizza_site import views as about
from pizza_products import views
from rest_framework_swagger.views import get_swagger_view
from django.conf.urls import url
from django.contrib.auth import views as authViews

schema_view = get_swagger_view(title='Pastebin API')
urlpatterns = [
        path('ckeditor/', include('ckeditor_uploader.urls')),
        path('admin/', admin.site.urls),
        path('cart/', include('cart.urls')),
        path('orders/', include('orders.urls')),
        path('', include('pizza_products.urls')),
        path('', include('users.urls', namespace='accounts')),
        path('blog/', include('blog.urls')),
        path('about/',about.about_page, name='about'),
        path('cooks/', include('cooks.urls')),
        path('Topcooks/', include('cookTop.urls')),
        path('authentication/', authViews.LoginView.as_view(template_name='users/authentication.html'), name='auth'),
        path('exit/', authViews.LogoutView.as_view(template_name='users/exit.html'), name='exit'),
        path('pass-reset/', authViews.PasswordResetView.as_view(template_name='users/pass_reset.html'), name='pass-reset'),
        path('password_reset_confirm/<uidb64>/<token>/',
            authViews.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
            name='password_reset_confirm'),
        path('password_reset_done/',
            authViews.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
            name='password_reset_done'),
        path('password_reset_complete/',
            authViews.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
            name='password_reset_complete'),
      ] \
          + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
          + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.ShowNewsView.as_view(), name='blog-home'),
    path('user/<str:username>/', views.UserAllNewsView.as_view(), name='user-news'),
    path('user/<str:username>/<str:operation>/', views.change_friend, name='change-friend'),
    path('blog/<int:pk>/update/', views.UpdateNewsView.as_view(), name='news-update'),
    path('blog/<int:pk>/delete/', views.DeleteNewsView.as_view(), name='news-delete'),
    path('blog/<int:pk>/favourite/', views.favourite_post, name='favourite-post'),
    path('profile/create/', views.CreateNewsView.as_view(), name='news-create'),
    path('blog/<int:pk>/', views.post_detail, name='news-detail'),
    path('blog/review/<int:pk>/', views.AddReview.as_view(), name='review'),
    path('my-groups/', views.GroupListView.as_view(), name='my-groups'),

]

cart/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<product_id>', views.cart_add, name='cart_add'),
    path('remove/<product_id>', views.cart_remove, name='cart_remove'),
]

cookTop/urls.py
from django.urls import path

from .views import TopCooks


app_name = "cookTop"

# app_name will help us do a reverse look-up latter.
urlpatterns = [
    path('', TopCooks.as_view(), name='topCooks'),
]

orders/urls.py
from django.urls import path
from . import views


app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

users/urls.py
from django.urls import path, include, re_path
from users import views as userViews
from django.contrib.auth import views as authViews
from django.contrib.auth import views as auth_views
from .import views

app_name = "accounts"

urlpatterns = [
    path('profile/', userViews.profile, name='profile'),
    re_path(r'^account/(?P<user_id>[-\w]+)$', views.account, name="account"),
    path('registration/', userViews.register, name='reg'),
    # path('authentication/', authViews.LoginView.as_view(template_name='users/authentication.html'), name='auth'),
    # path('exit/', authViews.LogoutView.as_view(template_name='users/exit.html'), name='exit'),
    # path('pass-reset/', authViews.PasswordResetView.as_view(template_name='users/pass_reset.html'), name='pass-reset'),
    # path('password_reset_confirm/<uidb64>/<token>/',
    #     authViews.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
    #     name='password_reset_confirm'),
    # path('password_reset_done/',
    #     authViews.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
    #     name='password_reset_done'),
    # path('password_reset_complete/',
    #     authViews.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
    #     name='password_reset_complete'),
    path('profile/favourite/', userViews.favourite_list, name='favourite'),
    path('profile/options/', userViews.change, name='change'),

]

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 26)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label=u'Количество')
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from pizza_products.models import PizzaProduct
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)  # create a new cart object passing it the request object
    product = get_object_or_404(PizzaProduct, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(PizzaProduct, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    return render(request, 'pizzeria/cart.html', {'cart': cart})

templates/pizzeria/about_page.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    О нас
{% endblock %}
{% block content %}
<div class="row">
	<div class="col-12 mt-4 mb-5">
		<h1 class="text-center">О нас</h1>
	</div>
</div>
<div class="row">
	<div class="col-12 mb-3" style="line-height:5px;">
		<h3>Клуб любителей пиццы</h3>
		<p><i>Developer: Nuriya</i></p>
		<hr style="height:2px;border:none;color:#000;background-color:#000;">
	</div>
	<div class="col-12 mt-4">
		<p>Мы находимся на рынке более 10 лет. Наши пиццы известны почти всем. Мы знаем, как много любителей пиццы в нашей стране.
      Именно поэтому мы решили сделать этот прекрасный сайт, где люди могут не только попробовать наши лучшие пиццы, но и пообщаться просто друг с другом, обсудить свои лучшие покупки пиццы.</p>

	</div>
{% endblock %}

templates/pizzeria/cart.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Корзина
{% endblock %}


{% block content %}
    <div class="container">
        <div class="row" style="margin-top: 6%">
        <h2>Ваша корзина:
            <span class="badge pull-right">
                {% with total_items=cart|length %}
                    {% if cart|length > 0 %}
                        Ваш заказ:
                        <a href="{% url "cart:cart_detail" %}">
                            {{ total_items }} шт., {{ cart.get_total_price }} руб.
                        </a>
                        {% else %}
                        Корзина пуста.
                    {% endif %}
                {% endwith %}
            </span>
        </h2>
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>Пицца</th>
                        <th>Количество</th>
                        <th>Удалить</th>
                        <th>Цена</th>
                        <th>Итого</th>
                    </tr>
                </thead>
                <tbody>
                {% for item in cart %}
                    {% with pizza_product=item.product  %}

                        <tr>
                        <td>
                            <img src="{{ pizza_product.image.url }}" class="img-responsive">
                        </td>
                            <td>{{ pizza_product.name }}</td>
                            <td>
                                <form action="{% url "cart:cart_add" pizza_product.id %}" method="post">
                                    {% csrf_token %}
                                    {{ item.update_quantity_form.quantity }}
                                    {{ item.update_quantity_form.update }}
                                    <button type="submit" id="submit_btn" class="btn btn-success">
                                        Обновить
                                    </button>

                                </form>
                            </td>
                            <td>
                                <a href="{% url "cart:cart_remove" pizza_product.id %}">Удалить</a>
                            </td>
                            <td>руб. {{ item.price }}</td>
                            <td>руб. {{ item.total_price }}</td>
                        </tr>
                    {% endwith %}
                {% endfor %}
                <tr>
                    <td><b>Итого</b></td>
                    <td colspan="4"></td>
                    <td colspan="num"><b>руб. {{ cart.get_total_price }}</b></td>
                </tr>
                </tbody>
            </table>
        <p class="text-right">
            <a href="{% url "home" %}" class="btn btn-success">Продолжить покупки</a>
            {% if user.is_authenticated %}
                <a href="{% url "orders:order_create" %}" class="btn btn-primary">Оформить заказ</a>
            {% else %}
                Для заказа товара необходимо <a class="btn btn-primary" href="{% url 'auth' %}">войти</a>
            {% endif %}
        </p>
        </div>
    </div>
{% endblock %}

templates/pizzeria/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="category-wrap">
      <h3>Что можно найти на сайте?</h3>
      <ul>
        {% if user.is_authenticated %}
        <li><a href ="{%url 'accounts:profile'%}">Мой кабинет</a></li>
        {% endif %}
        <li><a href="{% url 'about' %}" >О нас</a></li>
        <li><a href="{% url 'cookTop:topCooks' %}">Топ повара</a></li>
        <li><a href="#123">Наши пиццы</a></li>
        <li><a href="{% url 'blog-home' %}">Блог</a></li>

      </ul>
    </div>
    <div class="section section-top">
        <div class="container">
            <div class="row">
                <div id="123" class="col-lg-12">
                    <h1 class="text-center">
                    Наша пицца
                    </h1>
                </div>
               {% for pizza in pizzas %}
                    <div class="col-lg-3">
                        <div class="product-item">
                            <div>
                                <img src="{{ pizza.image.url }}" class="img-responsive">
                            </div>

                            <h4>{{ pizza.name }}</h4>
                            <p>
                                {{ pizza.description|truncatechars_html:30 }}
                            </p>
                            <div class="mr-3">
                                <a class='btn btn-secondary btn-xs' href="{% url 'pizza-detail' pizza.id%}">Комментарии</a>
                            </div>
                            <div>
                                {{ pizza.price }} руб.
                            </div>
                                <form action="{% url 'cart:cart_add' pizza.id %}" method="post">
                                    {{ cart_product_form }}
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <button type="submit" id="submit_btn" class="btn btn-success">
                                            Добавить в корзину
                                        </button>
                                    </div>
                                </form>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/pizzeria/new_comment.html
{% extends 'base.html' %}

{% block title %}
{{ object.name }}
{% endblock %}

{% block content %}
<div class="alert alert-light card-info">
    <h1>{{ object.name }}</h1>
    <p class='information'>{{ object.description|safe }}</p>
    <div>
        <img class='pizzas_image' src="{{ object.image.url }}">
    </div>
    <p class='information'>{{ object.price|safe }}</p>
</div>
<div class="bg-white p-3 comment-div">
    {% if user.is_authenticated %}
    <div class="p-1">
        <form action="{% url 'pizzacomments' object.id %}" method="POST" class="d-flex align-items-center">
            {% csrf_token %}
            <div class="textarea-div">
                <textarea name="text" id="exampleFormControlTextarea1" rows="2" width="100%"></textarea>
            </div>
            <div class="button-div">
                <button class="btn">Отправить</button>
            </div>
        </form>
    </div>
    {% endif %}
    {% if object.comments.all %}
    <hr>
    <div class="p-2">
        {% for comments in object.comments.all %}
        <div class="row align-items-center p-1">
            <div class="comment-text">
                <a href="{% url 'user-news' comments.user %}">{{comments.user }}: </a><span>{{ comments.text }}</span>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endif %}
</div>

{% endblock %}