Pizza_site/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from blog import views
from cooks import views
from Pizza_site import views as about
from pizza_products import views
from rest_framework_swagger.views import get_swagger_view
from django.conf.urls import url
from django.contrib.auth import views as authViews

schema_view = get_swagger_view(title='Pastebin API')
urlpatterns = [
        path('ckeditor/', include('ckeditor_uploader.urls')),
        path('admin/', admin.site.urls),
        path('cart/', include('cart.urls')),
        path('orders/', include('orders.urls')),
        path('', include('pizza_products.urls')),
        path('', include('users.urls', namespace='accounts')),
        path('blog/', include('blog.urls')),
        path('about/',about.about_page, name='about'),
        path('cooks/', include('cooks.urls')),
        path('Topcooks/', include('cookTop.urls')),
        path('authentication/', authViews.LoginView.as_view(template_name='users/authentication.html'), name='auth'),
        path('exit/', authViews.LogoutView.as_view(template_name='users/exit.html'), name='exit'),
        path('pass-reset/', authViews.PasswordResetView.as_view(template_name='users/pass_reset.html'), name='pass-reset'),
        path('password_reset_confirm/<uidb64>/<token>/',
            authViews.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
            name='password_reset_confirm'),
        path('password_reset_done/',
            authViews.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
            name='password_reset_done'),
        path('password_reset_complete/',
            authViews.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
            name='password_reset_complete'),
      ] \
          + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
          + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.ShowNewsView.as_view(), name='blog-home'),
    path('user/<str:username>/', views.UserAllNewsView.as_view(), name='user-news'),
    path('user/<str:username>/<str:operation>/', views.change_friend, name='change-friend'),
    path('blog/<int:pk>/update/', views.UpdateNewsView.as_view(), name='news-update'),
    path('blog/<int:pk>/delete/', views.DeleteNewsView.as_view(), name='news-delete'),
    path('blog/<int:pk>/favourite/', views.favourite_post, name='favourite-post'),
    path('profile/create/', views.CreateNewsView.as_view(), name='news-create'),
    path('blog/<int:pk>/', views.post_detail, name='news-detail'),
    path('blog/review/<int:pk>/', views.AddReview.as_view(), name='review'),
    path('my-groups/', views.GroupListView.as_view(), name='my-groups'),

]

users/urls.py
from django.urls import path, include, re_path
from users import views as userViews
from django.contrib.auth import views as authViews
from django.contrib.auth import views as auth_views
from .import views

app_name = "accounts"

urlpatterns = [
    path('profile/', userViews.profile, name='profile'),
    re_path(r'^account/(?P<user_id>[-\w]+)$', views.account, name="account"),
    path('registration/', userViews.register, name='reg'),
    # path('authentication/', authViews.LoginView.as_view(template_name='users/authentication.html'), name='auth'),
    # path('exit/', authViews.LogoutView.as_view(template_name='users/exit.html'), name='exit'),
    # path('pass-reset/', authViews.PasswordResetView.as_view(template_name='users/pass_reset.html'), name='pass-reset'),
    # path('password_reset_confirm/<uidb64>/<token>/',
    #     authViews.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
    #     name='password_reset_confirm'),
    # path('password_reset_done/',
    #     authViews.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
    #     name='password_reset_done'),
    # path('password_reset_complete/',
    #     authViews.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
    #     name='password_reset_complete'),
    path('profile/favourite/', userViews.favourite_list, name='favourite'),
    path('profile/options/', userViews.change, name='change'),

]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    img = models.ImageField(default='default.jpg', upload_to='user_images')
    friends = models.ManyToManyField(User, related_name='friend', blank=True)

    @classmethod
    def add_friend(cls, user, new_friend):
        friend, created = cls.objects.get_or_create(
            user=user
        )
        friend.friends.add(new_friend)

    @classmethod
    def del_friend(cls, user, new_friend):
        friend, created = cls.objects.get_or_create(
            user=user
        )
        friend.friends.remove(new_friend)

    @receiver(post_save, sender=User)
    def create_profile(sender, instance, created, **kwards):
        if created:
            Profile.objects.create(user = instance)

    @receiver(post_save, sender=User)
    def save_profile(sender, instance, **kwards):
        instance.profile.save()

    def __str__(self):
        return f'Профайл {self.user.username}'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        image = Image.open(self.img.path)

        if image.width > 256 or image.height > 256:
            resize = (256,256)
            image.thumbnail(resize)
            image.save(self.img.path)

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        
class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']

class ProfileImage(forms.ModelForm):
    def __init__(self, *args, **kwards):
        super(ProfileImage, self).__init__(*args, **kwards)
        self.fields['img'].label = 'Изображение'

    class Meta:
        model = Profile
        fields = ['img']

users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from orders.models import Order, ItemInOrder
from users.models import Profile
from .forms import UserRegisterForm, ProfileImage, UserUpdateForm
from django.contrib import messages
from blog.models import News
from django.contrib.auth.decorators import login_required



def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Аккаунт {username} создан')
            return redirect('auth')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})


@login_required
def account(request, user_id):
    user = request.user
    my_orders = Order.objects.filter(user=user)
    orders_info = Order.objects.all()
    order_items = ItemInOrder.objects.all()
    return render(request, "users/account.html",
                  {"my_orders": my_orders, "order_items": order_items, "orders_info": orders_info})
@login_required
def profile(request):
    user = request.user
    posts = News.objects.filter(author=user)
    profile = Profile.objects.get(user=user)
    friends = profile.friends.all()
    count_of_visits = 0
    count_of_comments = 0
    for post in posts:
        count_of_visits += post.count
        count_of_comments += post.review.count()
    context = {
        'posts': posts,
        'count_of_posts': len(posts),
        'count_of_visits': count_of_visits,
        'count_of_comments': count_of_comments,
        'friends': friends,
        'subscribers': user.friend.all().count()
    }

    return render(request, 'users/profile.html', context)


@login_required
def change(request):
    if request.method == "POST":
        img_profile = ProfileImage(request.POST, request.FILES, instance=request.user.profile)
        update_user = UserUpdateForm(request.POST, instance=request.user)

        if img_profile.is_valid() and update_user.is_valid():
            img_profile.save()
            update_user.save()
            messages.success(request, 'Ваш аккаунт успешно обновлен!')
            return redirect('accounts:profile')
    else:
        img_profile = ProfileImage(instance=request.user.profile)
        update_user = UserUpdateForm(instance=request.user)

    data = {
        'img_profile': img_profile,
        'update_user': update_user,
    }

    return render(request, 'users/profile_change.html', data)

@login_required
def favourite_list(request):
    user = request.user
    favourite_list = user.favourite.all().order_by('-date')
    return render(request, 'users/favourite_list.html', {'favourite_list': favourite_list})

users/templates/users/account.html
{% extends "base.html" %}
{% load static %}
{% block title %}Мой счет{% endblock title %}

{% block content %}

  <section>
    <div class="content-section">

      <h3 class="single-blog-post">Вы вошли как {{ user.username }}</h3>
        <p>ID пользователя: {{ user.id }}</p>
        <p>Ваш email: {{ user.email }}</p>
            <br>
      <h3 class="single-blog-post">История заказов:</h3>

      {% for order in my_orders %}
        <strong>Номер заказа: {{ order.id }}</strong>
          {% for info in orders_info %}
                {% if order.id == info.id %}
                    <p>Адрес доставки: {{ info.address }}</p>
                    <p>Имя: {{ info.first_name }}</p>
                    <p>Фамилия: {{ info.last_name }}</p>
                    <p>Дата заказа: {{ info.created }}</p>


                {% endif %}
            {% endfor %}
        {% for item in order_items %}
          {% if order.id == item.order.id %}
           <p>{{ item.quantity }} X {{ item.product.name }} по {{ item.product.price }} руб.</p>
          {% endif %}
        {% endfor %}
            <br>
      {% endfor %}


      </div>
  </section>

{% endblock content %}

users/templates/users/authentication.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
Авторизация на сайте
{% endblock %}

{% block content %}
<div class="full-screen-div">
    <div class="form-section">
        <h2>Авторизация на сайте</h2>
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="text-right">
                <button class="btn btn-outline-secondary" type="submit">Войти</button>
            </div>
        </form>
        <hr>
        <p class="text-center">Забыли пароль? <a href="{% url 'pass-reset' %}">Восстановить пароль</a></p>
    </div>
</div>
{% endblock %}

users/templates/users/exit.html
{% extends 'base.html' %}
{% load static %}

{% load crispy_forms_tags %}
{% block title %}
Выход
{% endblock %}

{% block content %}
<div class="full-screen-div">
    <div class="form-section">
        <h2>Вы вышли с аккаунта</h2>
        <a href="{% url 'auth' %}">Войти снова</a>
    </div>
</div>

{% endblock %}

users/templates/users/favourite_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Избранное
{% endblock %}

{% block content %}
    <div class="">
        <h2>Избранное:</h2>
        <div class="row">
          <a href="{% url 'news-create' %}" class='btn btn-outline-secondary mt-3'>Добавить статью</a>
          <a href="{% url 'accounts:change' %}" class='btn btn-outline-secondary mt-3'>Редактировать профиль</a>
        </div>
        {% for post in favourite_list %}
        {% if post.img %}
        <div class="d-flex card-div">
            <div class="col-4 post-image-div p-0">
                <img src="{{ post.img.url }}">
            </div>
            <div class="col-8 p-3 d-flex flex-column justify-content-between">
                <div class="">
                    <h5>{{ post.title }}</h5>
                    <p>{{ post.text|truncatewords:30|safe }}</p>
                </div>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="row">
                        <img class='user_image' src="{{ post.author.profile.img.url }}">
                        <div class="mt-2">
                            <span class='text-muted'>{{ post.date|date:"d E Y в H:i" }}</span>
                            <p><b>Автор: </b><a href='{% url "user-news" post.author %}'>{{ post.author }}</a></p>
                        </div>
                    </div>
                    <div class="d-flex align-items-center">
                        <div class="mr-3">
                            <i class="far fa-eye"></i>
                            {{ post.count }}
                        </div>
                        <a class='btn btn-secondary' href="{% url 'news-detail' post.id %}">Читать</a>
                    </div>
                </div>
            </div>
        </div>
        {% else %}
        <div class="alert alert-light">
            <h2>{{ post.title }}</h2>
            <p>{{ post.text|truncatewords:30|safe }}</p>
            <div class="d-flex justify-content-between">
                <div class="row">
                    <img class='user_image' src="{{ post.author.profile.img.url }}">
                    <div class="mt-2">
                        <span class='text-muted'>{{ post.date|date:"d E Y в H:i" }}</span>
                        <p><b>Автор: </b><a href='{% url "user-news" post.author %}'>{{ post.author }}</a></p>
                    </div>
                </div>
                <div class="row align-items-center">
                    <div class="mr-3">
                        <i class="far fa-eye"></i>
                        {{ post.count }}
                    </div>
                    <div class="mr-3">
                        <a class='btn btn-secondary' href="{% url 'news-detail' post.id %}">Читать</a>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
        {% endfor %}
    </div>
    <div class="mt-3">
        {% include 'include/last_news.html' %}
    </div>
{% endblock %}

users/templates/users/pass_reset.html
{% extends 'base.html' %}
{% load static %}

{% load crispy_forms_tags %}
{% block title %}
Восстоновление пароля
{% endblock %}

{% block content %}
<div class="full-screen-div">
    <div class="form-section">
        <h2>Запрос нового пароля</h2>
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-danger" type="submit">Отправить</button>
        </form>
    </div>
</div>
{% endblock %}

users/templates/users/password_reset_complete.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Пароль обновлен
{% endblock %}

{% block content %}
<div class="full-screen-div">
    <div class="form-section">
        <h2>Вы успешно обновили пароль</h2>
        <p>Ваш пароль заменен на новый</p>
    </div>
</div>
{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
Запросить новый пароль
{% endblock %}

{% block content %}
<div class="full-screen-div">
    <div class="form-section">
        <h2>Запросить новый пароль</h2>
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-danger" type="submit">Отправить</button>
        </form>
    </div>
</div>
{% endblock %}

users/templates/users/password_reset_done.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
Запрос отправлен
{% endblock %}

{% block content %}
<div class="full-screen-div">
    <div class="form-section">
        <h2>Вы успешно отправили запрос</h2>
        <p>Мы отправили ваш новый пароль на почту!</p>
    </div>
</div>
{% endblock %}

users/templates/users/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
Личный кабинет
{% endblock %}

{% block content %}
<div class="form-section">
  <h2>Личный кабинет {{ user.username }}</h2>
  <div class="media text-muted pt-3 mb-3">
      <img class='rounded mr-2' style='width: 64px; height: 64px;' src="{{ user.profile.img.url }}">
      <p class='media-body pb-3 mb-0 lh-125 border-bottom border-gray'>
          <strong class='d-block text-gray-dark'>@{{ user.username }}</strong>
          <b>Email:</b> {{ user.email }}
      </p>
  </div>

  <div class="d-flex justify-content-around">
        <div class="profile-count-of-posts">
            <p><i class="far fa-user-circle"></i> {{ subscribers }}</p>
        </div>
        <div class="profile-count-of-posts">
            <p><i class="far fa-comment"></i> {{ count_of_comments }}</p>
        </div>
        <div class="profile-count-of-posts">
            <p><i class="fas fa-mail-bulk"></i> {{ count_of_posts }}</p>
        </div>
        <div class="profile-count-of-posts">
            <p><i class="far fa-eye"></i> {{ count_of_visits }}</p>
        </div>
    </div>
  {% if posts %}
  {% for post in posts %}
  <div class="alert alert-light">
      <h2>{{ post.title }}</h2>
      <p>{{ post.text|truncatewords:30|safe }}</p>
      <div class="d-flex justify-content-between">
          <div class="row">
              <img class='user_image' src="{{ post.author.profile.img.url }}">
              <div class="mt-2">
                  <span class='text-muted'>{{ post.date|date:"d E Y в H:i" }}</span>
                  <p><b>Автор: </b><a href='{% url "user-news" post.author %}'>{{ post.author }}</a></p>
              </div>
          </div>
          <div class="row align-items-center">
              {% if post.review.count %}
              <div class="mr-2">
                  <i class="far fa-comment"></i>
                  {{ post.review.count }}
              </div>
              {% endif %}
              <div class="mr-3">
                  <i class="far fa-eye"></i>
                  {{ post.count }}
              </div>
              <div class="mr-3">
                  <a class='btn btn-secondary' href="{% url 'news-detail' post.id %}">Читать</a>
              </div>
          </div>
      </div>
  </div>
  {% endfor %}
  {% else %}
  <div style='text-align:center;' class="alert alert-light p-5">
      <h3>Тут будут отображаться ваши посты</h3>
      <a href="{% url 'news-create' %}" class='btn btn-outline-secondary mt-4'>Добавить пост</a>
  </div>
  {% endif %}
  </div>
    <div class="d-flex justify-content-around mt-3">
        <a href="{% url 'news-create' %}" class='btn btn-outline-secondary'>Добавить статью</a>
        <a href="{% url 'accounts:change' %}" class='btn btn-outline-secondary'>Редактировать профиль</a>
        <a href="{% url 'accounts:favourite' %}" class='btn btn-outline-secondary'>Избранное</a>
    </div>
    <hr>
    <div class="mt-3">
      {% include 'include/last_news.html' %}
  </div>
{% endblock %}

users/templates/users/profile_change.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}


{% block title %}
Личный кабинет
{% endblock %}

{% block content %}
<div class="full-screen-div">
  <div class="form-section">
      <h4>Изменить данные пользователя</h4>
      <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          {{ update_user|crispy }}
          <hr>
          {{ img_profile }}
          <div class="mt-3 text-right">
              <button class="btn btn-outline-secondary" type="submit">Обновить</button>
          </div>
      </form>
  </div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Зарегистрируйте аккаунт</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Зарегистрироваться</button>
            </div>

        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Уже есть аккаунт? <a class="=ml-2" href="{% url 'auth' %}">Войти</a>
            </small>
        </div>
    </div>

{% endblock %}