Pizza_site/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from blog import views
from cooks import views
from Pizza_site import views as about
from pizza_products import views
from rest_framework_swagger.views import get_swagger_view
from django.conf.urls import url
from django.contrib.auth import views as authViews

schema_view = get_swagger_view(title='Pastebin API')
urlpatterns = [
        path('ckeditor/', include('ckeditor_uploader.urls')),
        path('admin/', admin.site.urls),
        path('cart/', include('cart.urls')),
        path('orders/', include('orders.urls')),
        path('', include('pizza_products.urls')),
        path('', include('users.urls', namespace='accounts')),
        path('blog/', include('blog.urls')),
        path('about/',about.about_page, name='about'),
        path('cooks/', include('cooks.urls')),
        path('Topcooks/', include('cookTop.urls')),
        path('authentication/', authViews.LoginView.as_view(template_name='users/authentication.html'), name='auth'),
        path('exit/', authViews.LogoutView.as_view(template_name='users/exit.html'), name='exit'),
        path('pass-reset/', authViews.PasswordResetView.as_view(template_name='users/pass_reset.html'), name='pass-reset'),
        path('password_reset_confirm/<uidb64>/<token>/',
            authViews.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
            name='password_reset_confirm'),
        path('password_reset_done/',
            authViews.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
            name='password_reset_done'),
        path('password_reset_complete/',
            authViews.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
            name='password_reset_complete'),
      ] \
          + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
          + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.ShowNewsView.as_view(), name='blog-home'),
    path('user/<str:username>/', views.UserAllNewsView.as_view(), name='user-news'),
    path('user/<str:username>/<str:operation>/', views.change_friend, name='change-friend'),
    path('blog/<int:pk>/update/', views.UpdateNewsView.as_view(), name='news-update'),
    path('blog/<int:pk>/delete/', views.DeleteNewsView.as_view(), name='news-delete'),
    path('blog/<int:pk>/favourite/', views.favourite_post, name='favourite-post'),
    path('profile/create/', views.CreateNewsView.as_view(), name='news-create'),
    path('blog/<int:pk>/', views.post_detail, name='news-detail'),
    path('blog/review/<int:pk>/', views.AddReview.as_view(), name='review'),
    path('my-groups/', views.GroupListView.as_view(), name='my-groups'),

]

cart/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<product_id>', views.cart_add, name='cart_add'),
    path('remove/<product_id>', views.cart_remove, name='cart_remove'),
]

users/urls.py
from django.urls import path, include, re_path
from users import views as userViews
from django.contrib.auth import views as authViews
from django.contrib.auth import views as auth_views
from .import views

app_name = "accounts"

urlpatterns = [
    path('profile/', userViews.profile, name='profile'),
    re_path(r'^account/(?P<user_id>[-\w]+)$', views.account, name="account"),
    path('registration/', userViews.register, name='reg'),
    # path('authentication/', authViews.LoginView.as_view(template_name='users/authentication.html'), name='auth'),
    # path('exit/', authViews.LogoutView.as_view(template_name='users/exit.html'), name='exit'),
    # path('pass-reset/', authViews.PasswordResetView.as_view(template_name='users/pass_reset.html'), name='pass-reset'),
    # path('password_reset_confirm/<uidb64>/<token>/',
    #     authViews.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
    #     name='password_reset_confirm'),
    # path('password_reset_done/',
    #     authViews.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
    #     name='password_reset_done'),
    # path('password_reset_complete/',
    #     authViews.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
    #     name='password_reset_complete'),
    path('profile/favourite/', userViews.favourite_list, name='favourite'),
    path('profile/options/', userViews.change, name='change'),

]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Pizza
        {% endblock %}
    </title>

    <!-- stylesheet -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

    <!-- scripts -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/b6d85b8ecc.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">


</head>
<body>


    <div class="wrapper">
        <div class="wrapper-content">
            {% include 'navbar.html' %}
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                    </div>
                {% endfor %}
            {% endif %}

            {% block content %}
            {% endblock content %}
        </div>
    </div>
         {% include 'footer.html' %}

</body>
</html>

templates/footer.html
<footer class="footer">
    <div class="container">
        <div class="text">
            <h3>Как с нами связаться?</h3>
            <h4>Адрес: Россия, г. Казань ул. ул. Кремлёвская, 35</h4>
            <h4>Телефон: 89271234164</h4>
            <h4>Email 123@gmail.com</h4>
        </div>
    </div>
</footer>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url "home" %}">
  <img src="/static/media/logo.jpg" width="30" height="30" class="d-inline-block align-top" alt="">
  Клуб любителей пиццы</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto"></ul>
      <div class="basket-container">
        <a class="navbar-brand" href="{% url "cart:cart_detail" %}">Корзина</a>
     </div>

<div class="btn-group" role="group" aria-label="Button group with nested dropdown">
  <div class="btn-group" role="group">
    {% if user.is_authenticated %}
      <button id="btnGroupDrop1" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      {{ user.username }}
      </button>
      <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
        <a class="dropdown-item" href ="{%url 'accounts:profile'%}">Мой кабинет</a>
        <a class="dropdown-item" href="{% url 'my-groups' %}">Группы</a>
        <a class="dropdown-item" href="{% url 'accounts:account' user.id  %}">История заказов</a>
        <a class="dropdown-item" href="{% url 'exit' %}">Выйти</a>
      </div>
    {% else %}
      <button id="btnGroupDrop1" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Кто вы?
      </button>
      <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
        <a class="dropdown-item" href="{% url 'auth' %}">Войти</a>
        <a class="dropdown-item" href="{% url 'accounts:reg' %}">Зарегистрироваться</a>
      </div>
    {% endif %}

</div>
</div>
</nav>